
export enum ToolType {
  DASHBOARD = 'dashboard',
  NET_WORTH = 'net-worth-command-center',
  EMERGENCY_FUND = 'emergency-fund-guard',
  EMI_CALC = 'loan-emi-calculator',
  SALARY_CALC = 'salary-tax-estimator',
  INVESTMENT_CALC = 'wealth-investment-projector',
  MARKET_INSIGHTS = 'market-intelligence-pulse',
  LOAN_COMPARE = 'loan-comparison-tool',
  LIVING_COST = 'cost-of-living-calculator',
  MORTGAGE_CALC = 'mortgage-payment-calculator',
  CURRENCY_CONV = 'currency-exchange-intel',
  GST_CALC = 'gst-tax-calculator',
  CREDIT_CARD_PAYOFF = 'credit-card-debt-strategist',
  FIRE_PLANNER = 'early-retirement-fire-planner',
  FREELANCE_PROFIT = 'freelance-profit-hub',
  INVESTMENT_ACADEMY = 'investment-funds-academy',
  EXCEL_MODELER = 'excel-power-modeler',
  RETIREMENT_OPTIMIZER = 'retirement-account-optimizer',
  DRIP_CALCULATOR = 'dividend-reinvestment-calculator',
  CRYPTO_TAX_LOSS = 'crypto-tax-loss-harvester',
  CHILD_TAX_CREDIT = 'child-tax-credit-calculator',
  QUARTERLY_TAX = 'quarterly-estimated-tax-calculator',
  ACA_SUBSIDY = 'aca-health-insurance-subsidy-calculator',
  DTI_CALCULATOR = 'debt-to-income-ratio-calculator',
  OPTIONS_STRATEGY_VISUALIZER = 'options-strategy-visualizer',
  VALUATION_ACADEMY = 'valuation-academy',
  ACADEMY_DCF_GUIDE = 'academy/dcf-valuation-complete-guide',
  ACADEMY_WACC_GUIDE = 'academy/wacc-cost-of-capital-explained',
  ACADEMY_GREEKS_GUIDE = 'academy/options-greeks-delta-theta-vega-gamma',
  ACADEMY_SAFE_HARBOR = 'academy/safe-harbor-estimated-taxes',
  ACADEMY_IRON_CONDOR = 'academy/iron-condor-strategy-guide',
  ACADEMY_STATE_TAX_COMPARISON = 'academy/california-texas-take-home-comparison',
  BLOG_CTC_2025 = 'blog/child-tax-credit-2025-guide',
  BLOG_ACA_FREELANCERS = 'blog/aca-health-insurance-freelancers-2025',
  BLOG_QUARTERLY_TAX = 'blog/quarterly-estimated-taxes-complete-guide',
  BLOG_SE_TAX = 'blog/self-employment-tax-guide-2025',
  BLOG_TAX_DEDUCTIONS = 'blog/tax-deductions-freelancers-2025',
  BLOG_1099_W2 = 'blog/1099-vs-w2-comparison-2025',
  BLOG_LLC_SOLE_PROP = 'blog/llc-vs-sole-proprietor-2025',
  BLOG_SEP_SOLO401K = 'blog/sep-ira-vs-solo-401k-2025',
  BLOG_HOME_OFFICE = 'blog/home-office-deduction-2025',
  BLOG_MORTGAGE_GUIDE = 'blog/mortgage-calculator-guide-2025',
  BLOG_HOW_MUCH_HOUSE = 'blog/how-much-house-can-i-afford-2025',
  BLOG_DEBT_OR_INVEST = 'blog/should-i-pay-off-debt-or-invest-2025',
  BLOG_TAKE_HOME_PAY = 'blog/how-to-calculate-take-home-pay-2025',
  BLOG_CA_TX_TAKE_HOME = 'blog/100k-california-vs-texas-take-home-pay',
  BLOG_BONUS_TAX = 'blog/bonus-tax-myth-withholding-vs-liability',
  BLOG_RAISE_MOVE = 'blog/raise-vs-relocation-cost-of-living',
  BLOG_MAX_401K = 'blog/max-out-401k-take-home-pay',
  BLOG_GROSS_NET = 'blog/gross-vs-net-pay-paycheck-breakdown',
  BLOG_FREELANCE_ESTIMATED = 'blog/freelancer-estimated-taxes-guide-2025',
  BLOG_FLORIDA_MOVE = 'blog/moving-to-florida-sunshine-tax-savings',
  BLOG_PITI_EXPLAINED = 'blog/piti-explained-mortgage-payment-breakdown',
  BLOG_POINTS_BREAK_EVEN = 'blog/mortgage-points-break-even-2026',
  BLOG_PMI_MATH = 'blog/pmi-math-how-to-remove-faster',
  BLOG_RENT_BUY_2026 = 'blog/rent-vs-buy-5-percent-rule-2026',
  BLOG_500K_COST = 'blog/500k-house-monthly-cost-rate-sensitivity',
  BLOG_BIWEEKLY = 'blog/biweekly-mortgage-payments-interest-savings',
  BLOG_FI_NUMBER = 'blog/fi-number-math-financial-independence',
  BLOG_LEAN_FAT_FIRE = 'blog/leanfire-vs-fatfire-lifestyle-budget',
  BLOG_FOUR_PERCENT = 'blog/4-percent-rule-dead-safe-withdrawal-rates',
  BLOG_COAST_FIRE = 'blog/coast-fire-how-to-retire-early',
  BLOG_COST_WAITING = 'blog/cost-of-waiting-compound-interest',
  BLOG_ROTH_TRAD_401K = 'blog/roth-vs-traditional-401k-tax-bracket-bet',
  BLOG_SNOWBALL_AVALANCHE = 'blog/snowball-vs-avalanche-debt-payoff',
  BLOG_CAR_LOAN_72 = 'blog/72-month-car-loan-true-cost',
  BLOG_STUDENT_LOAN_REFI = 'blog/student-loan-refinance-math',
  BLOG_CC_MIN_PAY = 'blog/credit-card-minimum-payments-20-years',
  BLOG_ASSETS_LIABILITIES = 'blog/assets-vs-liabilities-true-net-worth',
  BLOG_ORDER_OPS = 'blog/financial-order-of-operations',
  BLOG_INFLATION_MILLION = 'blog/inflation-calculator-million-worth-retirement',
  BLOG_EMERGENCY_RULE = 'blog/6-month-emergency-fund-rule',
  BLOG_LATTE_FACTOR = 'blog/latte-factor-vs-big-wins-wealth',
  BLOG_DCF_RETAIL = 'blog/dcf-modeling-retail-investors',
  BLOG_LUMP_SUM_DCA = 'blog/lump-sum-vs-dollar-cost-averaging',
  BLOG_ROTH_TRADITIONAL = 'blog/roth-ira-vs-traditional-ira-2025',
  BLOG_EMERGENCY_FUND = 'blog/how-much-emergency-fund-do-i-need-2025',
  BLOG_FIRE_GUIDE = 'blog/fire-calculator-guide-2025',
  BLOG_BEST_RETIREMENT = 'blog/best-retirement-calculator-2025',
  BLOG_INVESTMENT_GUIDE = 'blog/investment-calculator-guide-2025',
  BLOG_BEST_MORTGAGE = 'blog/best-mortgage-calculator-2025',
  BLOG_STUDENT_LOANS = 'blog/student-loan-repayment-strategies-2025',
  BLOG_TAX_BRACKETS = 'blog/tax-brackets-explained-2025',
  BLOG_401K_VS_IRA = 'blog/401k-vs-ira-comparison-2025',
  BLOG_BUDGETING = 'blog/budgeting-guide-2025',
  BLOG_NET_WORTH = 'blog/net-worth-tracker-guide-2025',
  BLOG_EMI_GUIDE = 'blog/loan-emi-calculator-guide-2025',
  BLOG_LOAN_COMPARE = 'blog/loan-comparison-refinance-guide-2025',
  BLOG_LIVING_COST = 'blog/cost-of-living-calculator-guide-2025',
  BLOG_CURRENCY_CONVERTER = 'blog/currency-converter-guide-2025',
  BLOG_GST_GUIDE = 'blog/gst-tax-calculator-guide-2025',
  BLOG_CREDIT_CARD_PAYOFF = 'blog/credit-card-payoff-strategy-guide-2025',
  BLOG_MARKET_INSIGHTS = 'blog/ai-market-insights-guide-2025',
  BLOG_INVESTMENT_ACADEMY = 'blog/index-funds-etf-guide-2025',
  BLOG_EXCEL_MODELER = 'blog/dcf-valuation-modeling-guide-2025',
  BLOG_DRIP_GUIDE = 'blog/dividend-reinvestment-calculator-guide-2025',
  BLOG_DTI_GUIDE = 'blog/dti-calculator-guide-2025',
  BLOG_CRYPTO_WASH_SALE = 'blog/no-wash-sale-rule-crypto-tax-loss-harvesting',
  BLOG_CAPITAL_GAINS = 'blog/capital-gains-tax-guide-2025',
  BLOG_INDEX = 'blog',
  FAQ = 'financial-knowledge-base',
  METHODOLOGY = 'methodology-assumptions',
  PRIVACY = 'privacy-policy',
  SITEMAP = 'sitemap',
  ABOUT = 'about-quantcurb',
  CONTACT = 'contact-us',
  DISCLAIMER = 'legal-disclaimer'
}

export interface MarketInsight {
  title: string;
  summary: string;
  impact: 'Positive' | 'Neutral' | 'Negative';
  date: string;
}

export interface CalculationResult {
  monthlyPayment: number;
  totalInterest: number;
  totalAmount: number;
}
