import React from 'react';
import { ToolType } from '../../types';

interface SafeHarborGuideProps {
  setActiveTool: (tool: ToolType) => void;
}

const SafeHarborGuide: React.FC<SafeHarborGuideProps> = ({ setActiveTool }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <div className="bg-gradient-to-br from-orange-900 via-red-900 to-slate-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-6">
          <button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="text-orange-300 hover:text-white font-semibold text-sm mb-4">← Back to Academy</button>
          <h1 className="text-5xl font-black mb-6">Safe Harbor Rules: Never Pay IRS Penalties Again</h1>
          <div className="flex gap-6 text-sm text-orange-200"><span>📚 10 min read</span><span>📊 Beginner</span><span>Updated: January 2026</span></div>
        </div>
      </div>

      <article className="max-w-4xl mx-auto px-6 py-16">
        <div className="bg-orange-600 text-white rounded-2xl p-6 mb-12 shadow-xl flex items-center justify-between">
          <div><p className="font-black text-xl mb-2">Calculate Your Safe Harbor Amount</p><p className="text-orange-200">Plus download a calendar with automatic reminders for all 4 quarterly deadlines</p></div>
          <button onClick={() => setActiveTool(ToolType.QUARTERLY_TAX)} className="bg-white text-orange-900 px-6 py-3 rounded-xl font-black hover:bg-orange-50 transition-all whitespace-nowrap">Open Calculator →</button>
        </div>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-4">What is Safe Harbor?</h2><p className="text-slate-700 leading-relaxed mb-4">Safe Harbor is an <strong>IRS provision that protects you from underpayment penalties</strong> - even if you end up owing more tax at year-end. It's a "minimum payment guarantee" that keeps you penalty-free.</p><div className="bg-emerald-50 border-l-4 border-emerald-600 p-6 rounded-r-xl my-6"><p className="text-lg font-bold text-emerald-900 mb-2">The Core Rule:</p><p className="text-slate-700">If you pay <strong>at least</strong> one of these amounts in quarterly estimated taxes, the IRS won't penalize you:</p><ul className="list-disc list-inside mt-3 space-y-2 text-slate-700"><li><strong>100% of prior year tax</strong> (110% if AGI > $150K)</li><li><strong>90% of current year tax</strong></li></ul></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">The Two Safe Harbor Methods</h2><div className="grid md:grid-cols-2 gap-6"><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-emerald-600"><h3 className="text-2xl font-black text-emerald-900 mb-4">Prior Year Method</h3><p className="text-sm text-emerald-700 font-bold mb-4">RECOMMENDED ✓</p><p className="text-slate-700 mb-4">Pay 100% of last year's tax liability (110% if AGI > $150K)</p><div className="bg-emerald-50 rounded-xl p-4 mb-4"><p className="font-bold text-slate-900 mb-2">Example:</p><p className="font-mono text-sm text-slate-700">2025 Total Tax: $40,000</p><p className="font-mono text-sm text-slate-700">2026 Safe Harbor: $40,000 ÷ 4 = $10,000/quarter</p></div><div className="space-y-2 text-sm"><p className="text-emerald-900"><strong>Pros:</strong></p><ul className="list-disc list-inside text-slate-600 ml-4"><li>Simple - just look at last year's 1040</li><li>Predictable - same amount each quarter</li><li>No guessing about current year income</li></ul><p className="text-slate-600 mt-3"><strong>Best for:</strong> Stable income or income increasing</p></div></div><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-blue-600"><h3 className="text-2xl font-black text-blue-900 mb-4">Current Year Method</h3><p className="text-sm text-blue-700 font-bold mb-4">ADVANCED</p><p className="text-slate-700 mb-4">Pay 90% of this year's estimated tax liability</p><div className="bg-blue-50 rounded-xl p-4 mb-4"><p className="font-bold text-slate-900 mb-2">Example:</p><p className="font-mono text-sm text-slate-700">2026 Estimated Tax: $30,000</p><p className="font-mono text-sm text-slate-700">Safe Harbor: $30,000 × 90% = $27,000</p><p className="font-mono text-sm text-slate-700">Quarterly: $27,000 ÷ 4 = $6,750</p></div><div className="space-y-2 text-sm"><p className="text-blue-900"><strong>Pros:</strong></p><ul className="list-disc list-inside text-slate-600 ml-4"><li>Lower payments if income decreasing</li><li>Better cash flow management</li></ul><p className="text-red-600 mt-3"><strong>Risk:</strong> If you underestimate income, you pay penalties</p><p className="text-slate-600"><strong>Best for:</strong> Income significantly lower than last year</p></div></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Real-World Example: Freelancer Income Jump</h2><div className="bg-gradient-to-br from-slate-900 to-orange-900 text-white rounded-2xl p-8"><h3 className="text-2xl font-black mb-4">Case Study: Sarah the Consultant</h3><div className="bg-white/10 rounded-xl p-6 mb-6"><p className="text-orange-200 mb-4"><strong>Scenario:</strong></p><ul className="space-y-2 text-sm text-slate-200"><li>2025 Income: $80,000 → Total Tax: $15,000</li><li>2026 Income: $150,000 (doubled her clients!)</li><li>2026 Actual Tax Owed: $35,000</li></ul></div><div className="space-y-4"><div className="bg-emerald-900/30 rounded-xl p-4 border-2 border-emerald-500"><p className="font-bold text-emerald-400 mb-2">Sarah chooses Prior Year Safe Harbor:</p><p className="text-sm text-slate-200">Pays $15,000 total ($3,750/quarter)</p><p className="text-sm text-emerald-300 mt-2">✓ No penalties even though she owes $35K</p><p className="text-sm text-slate-300 mt-2">April 15, 2027: Pays remaining $20,000 penalty-free</p></div><div className="bg-red-900/30 rounded-xl p-4 border-2 border-red-500"><p className="font-bold text-red-400 mb-2">If Sarah paid nothing quarterly:</p><p className="text-sm text-slate-200">Owes $35,000 at year-end</p><p className="text-sm text-red-300 mt-2">✗ Underpayment penalty: ~8% × $35K = $2,800</p><p className="text-sm text-slate-300 mt-2">Total owed: $37,800</p></div></div><p className="text-orange-200 mt-6 text-sm"><strong>Lesson:</strong> Paying the $15K safe harbor saves $2,800 in penalties.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Quarterly Tax Deadlines (2026)</h2><div className="grid md:grid-cols-2 gap-4"><div className="bg-white rounded-xl p-6 shadow-lg"><p className="font-black text-lg text-indigo-900 mb-2">Q1 - January-March</p><p className="text-slate-700 font-bold">Due: April 15, 2026</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="font-black text-lg text-indigo-900 mb-2">Q2 - April-May</p><p className="text-slate-700 font-bold">Due: June 16, 2026</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="font-black text-lg text-indigo-900 mb-2">Q3 - June-August</p><p className="text-slate-700 font-bold">Due: September 15, 2026</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="font-black text-lg text-indigo-900 mb-2">Q4 - September-December</p><p className="text-slate-700 font-bold">Due: January 15, 2027</p></div></div><div className="bg-orange-50 border-l-4 border-orange-600 rounded-r-xl p-6 mt-6"><p className="font-bold text-orange-900 mb-2">💡 Pro Tip: Download Calendar Reminders</p><p className="text-orange-800">Our calculator generates an .ics file with 7-day advance alerts for all 4 deadlines. One click, never miss a payment.</p><button onClick={() => setActiveTool(ToolType.QUARTERLY_TAX)} className="mt-3 text-orange-700 font-bold hover:underline">→ Download Calendar Now</button></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">The HYSA Arbitrage Strategy</h2><div className="bg-gradient-to-br from-indigo-900 to-purple-900 text-white rounded-2xl p-8"><h3 className="text-2xl font-black mb-4">🎯 Advanced Cash Flow Optimization</h3><p className="text-indigo-200 mb-6">Here's how sophisticated freelancers use Safe Harbor to earn interest on tax money:</p><div className="bg-white/10 rounded-xl p-6 space-y-4"><p className="font-bold text-lg">The Strategy:</p><ol className="list-decimal list-inside space-y-3 text-sm text-slate-200"><li>Calculate <strong>minimum</strong> safe harbor amount (100% prior year)</li><li>Pay only that amount quarterly ($15,000 in Sarah's example)</li><li>Estimate you'll owe more at year-end ($35,000 actual)</li><li>Put the difference ($20,000) in a <strong>High Yield Savings Account</strong> at 4.5%</li><li>Earn interest for 8-10 months until April deadline</li><li>Pay remaining balance from HYSA in April - keep the interest</li></ol></div><div className="bg-emerald-900/30 rounded-xl p-6 mt-6 border-2 border-emerald-500"><p className="font-bold text-emerald-400 mb-3">Sarah's HYSA Profit:</p><p className="font-mono text-sm text-slate-200">$20,000 × 4.5% × (9 months / 12) = $675</p><p className="text-emerald-300 mt-2">✓ No penalties (safe harbor protected)</p><p className="text-emerald-300">✓ Earned $675 in interest</p><p className="text-emerald-300">✓ Had liquidity for 9 months</p></div><p className="text-purple-200 mt-6 text-sm"><strong>Why this works:</strong> IRS doesn't charge interest/penalties if you meet safe harbor, even if you owe more. Meanwhile, your money earns 4-5% in HYSA.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Common Mistakes to Avoid</h2><div className="space-y-4"><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Paying Nothing Because "I'll Owe Less This Year"</h3><p className="text-red-800">Even if you expect lower income, pay safe harbor to avoid penalties. You can always get a refund. Penalties are non-negotiable.</p></div><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Using Last Year's Withholding Instead of Total Tax</h3><p className="text-red-800">Safe harbor is 100% of <strong>total tax liability</strong> (line 24 on Form 1040), not just what was withheld. Include self-employment tax!</p></div><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Missing Just One Quarterly Payment</h3><p className="text-red-800">IRS calculates penalties per quarter. Missing Q2 but paying Q3/Q4 doesn't help - you still owe Q2 penalties. Pay all 4 on time.</p></div><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Not Adjusting for AGI > $150K</h3><p className="text-red-800">High earners must pay 110% of prior year, not 100%. Missing this extra 10% = penalties despite thinking you're safe.</p></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Who Needs to Pay Quarterly Taxes?</h2><div className="bg-slate-100 rounded-xl p-6"><p className="font-bold text-slate-900 mb-4">You must pay quarterly if:</p><ul className="space-y-2 text-slate-700"><li className="flex items-start gap-3"><span className="text-orange-600 font-black text-xl">•</span><span>You're <strong>self-employed</strong> (freelancer, consultant, contractor)</span></li><li className="flex items-start gap-3"><span className="text-orange-600 font-black text-xl">•</span><span>You have <strong>1099 income</strong> without withholding</span></li><li className="flex items-start gap-3"><span className="text-orange-600 font-black text-xl">•</span><span>You expect to owe <strong>$1,000+</strong> at year-end</span></li><li className="flex items-start gap-3"><span className="text-orange-600 font-black text-xl">•</span><span>You have <strong>rental income, dividends, capital gains</strong></span></li><li className="flex items-start gap-3"><span className="text-orange-600 font-black text-xl">•</span><span>Your withholding will cover <strong>less than 90%</strong> of current year tax</span></li></ul></div></section>

        <section className="mb-12"><div className="bg-gradient-to-br from-orange-600 to-red-600 text-white rounded-2xl p-12 text-center"><h2 className="text-4xl font-black mb-4">Calculate Your Safe Harbor Amount Now</h2><p className="text-xl text-orange-100 mb-8">Get your exact quarterly payment + download a calendar with 7-day advance reminders</p><button onClick={() => setActiveTool(ToolType.QUARTERLY_TAX)} className="bg-white text-orange-900 px-10 py-5 rounded-xl font-black text-xl hover:bg-orange-50 transition-all shadow-2xl">Open Safe Harbor Calculator →</button></div></section>

        <section><h2 className="text-3xl font-black text-slate-900 mb-6">Continue Learning</h2><div className="grid md:grid-cols-3 gap-6"><button onClick={() => setActiveTool(ToolType.ACADEMY_STATE_TAX_COMPARISON)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-orange-500"><div className="text-3xl mb-3">🗺️</div><h3 className="font-black text-slate-900 mb-2">State Tax Comparison</h3><p className="text-slate-600 text-sm">CA vs TX take-home analysis</p></button><button onClick={() => setActiveTool(ToolType.ACADEMY_DCF_GUIDE)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-orange-500"><div className="text-3xl mb-3">📊</div><h3 className="font-black text-slate-900 mb-2">DCF Valuation</h3><p className="text-slate-600 text-sm">Stock valuation fundamentals</p></button><button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-orange-500"><div className="text-3xl mb-3">🎓</div><h3 className="font-black text-slate-900 mb-2">All Guides</h3><p className="text-slate-600 text-sm">Back to Academy</p></button></div></section>
      </article>
    </div>
  );
};

export default SafeHarborGuide;
