import React from 'react';
import { ToolType } from '../../types';

interface StateTaxComparisonProps {
  setActiveTool: (tool: ToolType) => void;
}

const StateTaxComparison: React.FC<StateTaxComparisonProps> = ({ setActiveTool }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <div className="bg-gradient-to-br from-blue-900 via-cyan-900 to-slate-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-6">
          <button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="text-blue-300 hover:text-white font-semibold text-sm mb-4">← Back to Academy</button>
          <h1 className="text-5xl font-black mb-6">California vs Texas: Real Take-Home Pay Analysis</h1>
          <div className="flex gap-6 text-sm text-blue-200"><span>📚 8 min read</span><span>📊 Beginner</span><span>Updated: January 2026</span></div>
        </div>
      </div>

      <article className="max-w-4xl mx-auto px-6 py-16">
        <div className="bg-blue-600 text-white rounded-2xl p-6 mb-12 shadow-xl flex items-center justify-between">
          <div><p className="font-black text-xl mb-2">Compare Any Two States</p><p className="text-blue-200">Calculate exact take-home pay for all 50 states + DC</p></div>
          <button onClick={() => setActiveTool(ToolType.SALARY_CALC)} className="bg-white text-blue-900 px-6 py-3 rounded-xl font-black hover:bg-blue-50 transition-all whitespace-nowrap">Open Calculator →</button>
        </div>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-4">The $100K Question</h2><p className="text-slate-700 leading-relaxed mb-4">You've been offered two identical $100,000 jobs - one in San Francisco, one in Austin. Which pays more <strong>after taxes</strong>?</p><div className="bg-slate-100 border-l-4 border-blue-600 p-6 rounded-r-xl my-6"><p className="text-lg font-bold text-slate-900">Spoiler Alert:</p><p className="text-slate-700 mt-2">The Texas job gives you <strong className="text-emerald-600">$8,100+ more take-home</strong> every year - enough to buy a used car, max out an IRA, or make extra mortgage payments.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">The Math: $100K Salary Breakdown</h2><div className="grid md:grid-cols-2 gap-6"><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-red-600"><h3 className="text-2xl font-black text-red-900 mb-4">California 🐻</h3><div className="space-y-3 text-sm"><p className="text-slate-700 font-bold">Gross Salary: <span className="float-right">$100,000</span></p><p className="text-slate-600">Federal Tax: <span className="float-right text-slate-900">-$13,200</span></p><p className="text-slate-600">FICA (SS + Medicare): <span className="float-right text-slate-900">-$7,650</span></p><p className="text-red-600 font-bold">CA State Tax (9.3%): <span className="float-right text-red-900">-$5,500</span></p><p className="border-t-2 border-slate-300 pt-3 text-lg font-black text-slate-900">Take-Home Pay: <span className="float-right text-red-600">$73,650</span></p><p className="text-xs text-slate-500 mt-4">Monthly: $6,137 | Biweekly: $2,833</p></div></div><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-emerald-600"><h3 className="text-2xl font-black text-emerald-900 mb-4">Texas 🤠</h3><div className="space-y-3 text-sm"><p className="text-slate-700 font-bold">Gross Salary: <span className="float-right">$100,000</span></p><p className="text-slate-600">Federal Tax: <span className="float-right text-slate-900">-$13,200</span></p><p className="text-slate-600">FICA (SS + Medicare): <span className="float-right text-slate-900">-$7,650</span></p><p className="text-emerald-600 font-bold">TX State Tax (0%): <span className="float-right text-emerald-900">$0</span></p><p className="border-t-2 border-slate-300 pt-3 text-lg font-black text-slate-900">Take-Home Pay: <span className="float-right text-emerald-600">$79,150</span></p><p className="text-xs text-slate-500 mt-4">Monthly: $6,596 | Biweekly: $3,044</p></div></div></div><div className="bg-gradient-to-br from-emerald-900 to-teal-900 text-white rounded-2xl p-8 mt-8 text-center"><p className="text-3xl font-black mb-2">Texas Advantage: +$5,500/year</p><p className="text-emerald-200">That's $458/month or $211 per paycheck more in your pocket</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">But Wait - What About Cost of Living?</h2><p className="text-slate-700 mb-6">State income tax is just one piece. Let's look at the full picture:</p><div className="bg-white rounded-2xl p-8 shadow-lg"><div className="space-y-6"><div><p className="font-black text-slate-900 mb-3">🏠 Housing Costs</p><div className="grid md:grid-cols-2 gap-4 text-sm"><div className="bg-red-50 rounded-lg p-4"><p className="font-bold text-red-900">San Francisco</p><p className="text-slate-700 mt-1">1BR Apartment: $3,200/mo</p><p className="text-slate-600">Median Home: $1.4M</p></div><div className="bg-emerald-50 rounded-lg p-4"><p className="font-bold text-emerald-900">Austin</p><p className="text-slate-700 mt-1">1BR Apartment: $1,600/mo</p><p className="text-slate-600">Median Home: $550K</p></div></div><p className="text-indigo-600 font-bold mt-3">Austin saves: $1,600/month on rent</p></div><div><p className="font-black text-slate-900 mb-3">🚗 Transportation</p><div className="grid md:grid-cols-2 gap-4 text-sm"><div className="bg-red-50 rounded-lg p-4"><p className="font-bold text-red-900">California</p><p className="text-slate-700">Gas: $5.20/gal</p><p className="text-slate-700">Car Registration: $500+/year</p><p className="text-slate-600">Insurance: Higher due to regulations</p></div><div className="bg-emerald-50 rounded-lg p-4"><p className="font-bold text-emerald-900">Texas</p><p className="text-slate-700">Gas: $3.10/gal</p><p className="text-slate-700">Car Registration: $150/year</p><p className="text-slate-600">Insurance: Moderate</p></div></div></div><div><p className="font-black text-slate-900 mb-3">🛒 Sales Tax (The Twist)</p><p className="text-slate-700 text-sm mb-3">Texas makes up for no income tax with higher sales tax (8.25% vs CA's 7.25%). But you only pay sales tax on what you spend, not what you earn.</p><p className="text-indigo-600 font-bold text-sm">Advantage: Still Texas (you control spending, can't control income tax)</p></div></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">The Wealth-Building Impact Over 10 Years</h2><div className="bg-gradient-to-br from-slate-900 to-blue-900 text-white rounded-2xl p-8"><p className="text-xl font-black mb-6">What if you invested that $5,500/year tax savings?</p><div className="bg-white/10 rounded-xl p-6 space-y-3 text-sm"><p className="text-blue-200">Annual investment: $5,500 (CA-TX tax difference)</p><p className="text-blue-200">Market return: 10% (S&P 500 historical avg)</p><p className="text-blue-200">Time horizon: 10 years</p><p className="border-t border-white/20 mt-4 pt-4 text-2xl font-black text-emerald-400">Future Value: $95,624</p></div><p className="text-blue-200 mt-6 text-sm">By living in Texas instead of California on a $100K salary, you could build a nearly <strong className="text-yellow-300">six-figure investment portfolio</strong> from tax savings alone.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Other No-Tax States Worth Considering</h2><div className="grid md:grid-cols-3 gap-4"><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">☀️</p><h3 className="font-black text-slate-900 mb-1">Florida</h3><p className="text-slate-600 text-sm">0% state tax, warm weather, no state capital gains tax</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">🏔️</p><h3 className="font-black text-slate-900 mb-1">Wyoming</h3><p className="text-slate-600 text-sm">0% state tax, low property tax, outdoor paradise</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">🎰</p><h3 className="font-black text-slate-900 mb-1">Nevada</h3><p className="text-slate-600 text-sm">0% state tax, no corporate tax, Las Vegas/Reno tech hubs</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">🌲</p><h3 className="font-black text-slate-900 mb-1">Washington</h3><p className="text-slate-600 text-sm">0% income tax, strong tech scene (Amazon, Microsoft)</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">🦅</p><h3 className="font-black text-slate-900 mb-1">Alaska</h3><p className="text-slate-600 text-sm">0% state tax PLUS annual oil dividend (~$1,000-$2,000)</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><p className="text-3xl mb-2">🎿</p><h3 className="font-black text-slate-900 mb-1">New Hampshire</h3><p className="text-slate-600 text-sm">0% wage tax, only taxes dividends/interest</p></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">High-Tax States: When It Might Still Make Sense</h2><div className="bg-yellow-50 border-l-4 border-yellow-600 rounded-r-xl p-6 mb-6"><p className="font-bold text-yellow-900 mb-3">Not all high-tax states are bad deals:</p><ul className="space-y-2 text-slate-700 text-sm"><li><strong>New York:</strong> Finance jobs pay 30-50% premiums. $150K NYC salary > $100K Texas after COL adjustment</li><li><strong>Massachusetts:</strong> World-class healthcare, education, biotech salaries 20%+ higher</li><li><strong>California:</strong> Tech compensation ($200K+ RSUs) can outweigh 13.3% tax if you're senior engineer</li></ul></div><p className="text-slate-600 text-sm">The key question: <strong className="text-slate-900">Does the salary premium exceed the tax + COL difference?</strong> Use our calculator to find out.</p></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Tax Migration: The Exodus Data</h2><div className="bg-white rounded-2xl p-8 shadow-lg"><p className="text-slate-700 mb-4">IRS data shows net migration patterns (2020-2024):</p><div className="space-y-3"><div className="flex items-center justify-between bg-red-50 rounded-lg p-4"><span className="font-bold text-red-900">California</span><span className="text-red-600 font-mono">-341,000 taxpayers</span></div><div className="flex items-center justify-between bg-red-50 rounded-lg p-4"><span className="font-bold text-red-900">New York</span><span className="text-red-600 font-mono">-299,000 taxpayers</span></div><div className="flex items-center justify-between bg-red-50 rounded-lg p-4"><span className="font-bold text-red-900">Illinois</span><span className="text-red-600 font-mono">-263,000 taxpayers</span></div><div className="flex items-center justify-between bg-emerald-50 rounded-lg p-4 mt-4"><span className="font-bold text-emerald-900">Florida</span><span className="text-emerald-600 font-mono">+738,000 taxpayers</span></div><div className="flex items-center justify-between bg-emerald-50 rounded-lg p-4"><span className="font-bold text-emerald-900">Texas</span><span className="text-emerald-600 font-mono">+656,000 taxpayers</span></div><div className="flex items-center justify-between bg-emerald-50 rounded-lg p-4"><span className="font-bold text-emerald-900">Arizona</span><span className="text-emerald-600 font-mono">+263,000 taxpayers</span></div></div><p className="text-slate-600 text-sm mt-6">High earners are voting with their feet. Remote work has accelerated this trend - you can keep your CA tech salary while living in a no-tax state.</p></div></section>

        <section className="mb-12"><div className="bg-gradient-to-br from-blue-600 to-cyan-600 text-white rounded-2xl p-12 text-center"><h2 className="text-4xl font-black mb-4">Calculate Your State-by-State Take-Home</h2><p className="text-xl text-blue-100 mb-8">Compare all 50 states + DC with exact tax calculations for 2026</p><button onClick={() => setActiveTool(ToolType.SALARY_CALC)} className="bg-white text-blue-900 px-10 py-5 rounded-xl font-black text-xl hover:bg-blue-50 transition-all shadow-2xl">Open Salary Calculator →</button></div></section>

        <section><h2 className="text-3xl font-black text-slate-900 mb-6">Continue Learning</h2><div className="grid md:grid-cols-3 gap-6"><button onClick={() => setActiveTool(ToolType.ACADEMY_SAFE_HARBOR)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-blue-500"><div className="text-3xl mb-3">📅</div><h3 className="font-black text-slate-900 mb-2">Safe Harbor Tax</h3><p className="text-slate-600 text-sm">Never pay IRS penalties</p></button><button onClick={() => setActiveTool(ToolType.ACADEMY_DCF_GUIDE)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-blue-500"><div className="text-3xl mb-3">📊</div><h3 className="font-black text-slate-900 mb-2">DCF Valuation</h3><p className="text-slate-600 text-sm">Stock valuation guide</p></button><button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-blue-500"><div className="text-3xl mb-3">🎓</div><h3 className="font-black text-slate-900 mb-2">All Guides</h3><p className="text-slate-600 text-sm">Back to Academy</p></button></div></section>
      </article>
    </div>
  );
};

export default StateTaxComparison;
