import React from 'react';
import { ToolType } from '../../types';

interface WACCGuideProps {
  setActiveTool: (tool: ToolType) => void;
}

const WACCGuide: React.FC<WACCGuideProps> = ({ setActiveTool }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <div className="bg-gradient-to-br from-purple-900 via-indigo-900 to-slate-900 text-white py-16">
        <div className="max-w-4xl mx-auto px-6">
          <button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="text-purple-300 hover:text-white font-semibold text-sm mb-4">← Back to Academy</button>
          <h1 className="text-5xl font-black mb-6">WACC Explained: The Cost of Capital Demystified</h1>
          <div className="flex gap-6 text-sm text-purple-200"><span>📚 12 min read</span><span>📊 Intermediate</span><span>Updated: January 2026</span></div>
        </div>
      </div>

      <article className="max-w-4xl mx-auto px-6 py-16">
        <div className="bg-purple-600 text-white rounded-2xl p-6 mb-12 shadow-xl flex items-center justify-between">
          <div><p className="font-black text-xl mb-2">Calculate WACC in 60 Seconds</p><p className="text-purple-200">Our WACC Wizard includes CAPM calculator and one-click DCF integration</p></div>
          <button onClick={() => setActiveTool(ToolType.EXCEL_MODELER)} className="bg-white text-purple-900 px-6 py-3 rounded-xl font-black hover:bg-purple-50 transition-all whitespace-nowrap">Open WACC Wizard →</button>
        </div>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-4">What is WACC?</h2><p className="text-slate-700 leading-relaxed mb-4">WACC (Weighted Average Cost of Capital) is the <strong>average rate a company pays to finance its assets</strong>. It's the blended cost of both equity and debt, weighted by how much of each the company uses.</p><div className="bg-slate-100 border-l-4 border-purple-600 p-6 rounded-r-xl my-6"><p className="text-lg font-bold text-slate-900 italic">"WACC is the minimum return a company must earn on its investments to satisfy all its investors - both shareholders and creditors."</p></div><p className="text-slate-700">In DCF valuation, WACC is your <strong>discount rate</strong> - the hurdle that future cash flows must clear to create value today.</p></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">The WACC Formula</h2><div className="bg-gradient-to-br from-purple-900 to-indigo-900 text-white rounded-2xl p-8 mb-6"><p className="text-2xl font-black mb-4 text-center">WACC Formula</p><div className="bg-white/10 rounded-xl p-6 font-mono text-lg text-center">WACC = (E/(E+D) × Kₑ) + (D/(E+D) × Kd × (1 - Tax))</div><div className="mt-6 space-y-2 text-sm text-purple-200"><p><strong>E</strong> = Market value of equity</p><p><strong>D</strong> = Market value of debt</p><p><strong>Kₑ</strong> = Cost of equity (from CAPM)</p><p><strong>Kd</strong> = Cost of debt (interest rate on debt)</p><p><strong>Tax</strong> = Corporate tax rate</p></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Step 1: Calculate Cost of Equity (Kₑ) Using CAPM</h2><p className="text-slate-700 mb-4">The <strong>Capital Asset Pricing Model (CAPM)</strong> calculates the return shareholders expect based on risk.</p><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-purple-600 mb-6"><div className="bg-slate-50 rounded-xl p-4 font-mono text-center mb-4"><p className="text-xl text-slate-900">Kₑ = Rf + β(Rm - Rf)</p></div><div className="space-y-3 text-slate-700"><p><strong>Rf (Risk-Free Rate)</strong> = US 10-Year Treasury yield (currently ~4.2%)</p><p><strong>β (Beta)</strong> = Stock volatility vs market (Tech: 1.2, Finance: 1.1, Utilities: 0.7)</p><p><strong>Rm - Rf (Market Risk Premium)</strong> = Expected market return above risk-free (historical avg: 7%)</p></div></div><div className="bg-indigo-50 rounded-xl p-6"><p className="text-slate-900 font-bold mb-2">Example: Tech Company</p><p className="font-mono text-sm text-slate-700">Rf = 4.2% (10-yr Treasury)</p><p className="font-mono text-sm text-slate-700">β = 1.3 (high-growth tech)</p><p className="font-mono text-sm text-slate-700">Market Risk Premium = 7%</p><p className="font-mono text-lg text-indigo-900 font-bold mt-2">Kₑ = 4.2% + 1.3(7%) = 13.3%</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Step 2: Determine Cost of Debt (Kd)</h2><p className="text-slate-700 mb-4">Cost of debt is the <strong>effective interest rate</strong> a company pays on its borrowings.</p><div className="bg-white rounded-xl p-6 shadow-lg mb-4"><p className="font-bold text-slate-900 mb-3">Method 1: Use Current Yield to Maturity (Best)</p><p className="text-slate-700 mb-2">Look up the company's bonds and find the YTM. This reflects market expectations.</p><p className="font-mono text-sm text-slate-600">Example: Apple 10-yr bonds trading at YTM of 3.8%</p></div><div className="bg-white rounded-xl p-6 shadow-lg mb-4"><p className="font-bold text-slate-900 mb-3">Method 2: Interest Expense / Total Debt (Easier)</p><p className="text-slate-700 mb-2">From financial statements:</p><p className="font-mono text-sm text-slate-600">Kd = Interest Expense / (Short-term Debt + Long-term Debt)</p></div><div className="bg-slate-100 rounded-xl p-4"><p className="text-sm text-slate-600"><strong>Tax Shield:</strong> Debt interest is tax-deductible, so we multiply by (1 - Tax Rate) in the WACC formula. This makes debt cheaper than equity.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Step 3: Calculate Capital Structure Weights</h2><p className="text-slate-700 mb-4">WACC weights equity and debt by their <strong>market values</strong>, not book values.</p><div className="bg-white rounded-2xl p-8 shadow-lg border-l-8 border-indigo-600"><p className="font-bold text-slate-900 mb-4">Finding Market Values:</p><div className="space-y-3 text-slate-700"><p><strong>Market Value of Equity (E)</strong> = Share Price × Shares Outstanding</p><p className="text-sm text-slate-600">Example: $150/share × 100M shares = $15B</p><p className="mt-4"><strong>Market Value of Debt (D)</strong> = Total debt from balance sheet (approx)</p><p className="text-sm text-slate-600">Example: $5B in bonds + loans</p></div><div className="bg-slate-50 rounded-xl p-4 mt-6 font-mono text-sm"><p className="text-slate-700">Total Capital (E + D) = $15B + $5B = $20B</p><p className="text-slate-700 mt-2">Equity Weight = $15B / $20B = 75%</p><p className="text-slate-700">Debt Weight = $5B / $20B = 25%</p></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Full WACC Calculation Example</h2><div className="bg-gradient-to-br from-slate-900 to-purple-900 text-white rounded-2xl p-8"><h3 className="text-2xl font-black mb-4">Case Study: SaaS Company</h3><div className="space-y-2 text-purple-200 mb-6"><p><strong>Given:</strong></p><ul className="list-disc list-inside ml-4 space-y-1"><li>Market Cap (E): $10B</li><li>Total Debt (D): $2B</li><li>Cost of Equity (Kₑ): 12% (from CAPM)</li><li>Cost of Debt (Kd): 5% (bond YTM)</li><li>Tax Rate: 25%</li></ul></div><div className="bg-white/10 rounded-xl p-6 font-mono text-sm space-y-2"><p>Total Capital = $10B + $2B = $12B</p><p>Equity Weight (E/(E+D)) = $10B/$12B = 83.3%</p><p>Debt Weight (D/(E+D)) = $2B/$12B = 16.7%</p><p className="mt-4">Equity Component = 83.3% × 12% = 10.0%</p><p>Debt Component = 16.7% × 5% × (1-0.25) = 0.625%</p><p className="border-t border-white/20 mt-4 pt-2 text-lg font-bold text-emerald-400">WACC = 10.0% + 0.625% = 10.6%</p></div><p className="text-purple-200 mt-4 text-sm">This 10.6% is the discount rate to use in DCF valuation.</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Why WACC Matters in Valuation</h2><div className="grid md:grid-cols-2 gap-6"><div className="bg-white rounded-xl p-6 shadow-lg"><div className="text-3xl mb-3">📊</div><h3 className="font-black text-slate-900 mb-2">Discount Rate for DCF</h3><p className="text-slate-600 text-sm">WACC is THE discount rate in DCF models. A 1% change in WACC can swing valuation by 20-30%.</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><div className="text-3xl mb-3">🎯</div><h3 className="font-black text-slate-900 mb-2">Investment Hurdle Rate</h3><p className="text-slate-600 text-sm">Companies use WACC to evaluate projects. If ROI > WACC, the project creates value.</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><div className="text-3xl mb-3">⚖️</div><h3 className="font-black text-slate-900 mb-2">Capital Structure Optimization</h3><p className="text-slate-600 text-sm">Companies aim to minimize WACC through optimal debt/equity mix. Too much debt = bankruptcy risk.</p></div><div className="bg-white rounded-xl p-6 shadow-lg"><div className="text-3xl mb-3">📈</div><h3 className="font-black text-slate-900 mb-2">Risk Measure</h3><p className="text-slate-600 text-sm">Higher WACC = riskier company. Mature utilities: 6-8%. High-growth tech: 10-15%.</p></div></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">WACC Sensitivity: Why It's Critical</h2><p className="text-slate-700 mb-4">Small changes in WACC dramatically impact valuation. Always run sensitivity analysis.</p><div className="bg-slate-900 text-white rounded-xl p-6 overflow-x-auto"><table className="w-full text-sm font-mono"><thead><tr className="border-b border-white/20"><th className="text-left pb-3">WACC</th><th className="text-right pb-3">Enterprise Value</th><th className="text-right pb-3">% Change</th></tr></thead><tbody className="space-y-2"><tr><td>8%</td><td className="text-right">$12.5B</td><td className="text-right text-emerald-400">+25%</td></tr><tr><td>9%</td><td className="text-right">$11.2B</td><td className="text-right text-emerald-400">+12%</td></tr><tr className="bg-white/10"><td>10%</td><td className="text-right font-bold">$10.0B</td><td className="text-right text-slate-400">Base</td></tr><tr><td>11%</td><td className="text-right">$9.0B</td><td className="text-right text-red-400">-10%</td></tr><tr><td>12%</td><td className="text-right">$8.2B</td><td className="text-right text-red-400">-18%</td></tr></tbody></table><p className="text-purple-200 mt-4 text-sm">A 2% increase in WACC (10% → 12%) reduces value by 18%</p></div></section>

        <section className="mb-12"><h2 className="text-3xl font-black text-slate-900 mb-6">Common WACC Mistakes</h2><div className="space-y-4"><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Using Book Values Instead of Market Values</h3><p className="text-red-800">Never use balance sheet debt or equity. Always use market cap and bond prices for accuracy.</p></div><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Forgetting the Tax Shield on Debt</h3><p className="text-red-800">Debt interest is tax-deductible. Always multiply Kd by (1 - Tax Rate), not the full rate.</p></div><div className="bg-red-50 border-l-4 border-red-600 rounded-r-xl p-6"><h3 className="font-black text-red-900 mb-2">❌ Using Wrong Beta</h3><p className="text-red-800">Use levered beta (company-specific risk), not unlevered. Bloomberg/Yahoo Finance provide levered betas.</p></div></div></section>

        <section className="mb-12"><div className="bg-gradient-to-br from-purple-600 to-indigo-600 text-white rounded-2xl p-12 text-center"><h2 className="text-4xl font-black mb-4">Calculate WACC in 60 Seconds</h2><p className="text-xl text-purple-100 mb-8">Our WACC Wizard walks you through CAPM, capital structure, and one-click DCF integration</p><button onClick={() => setActiveTool(ToolType.EXCEL_MODELER)} className="bg-white text-purple-900 px-10 py-5 rounded-xl font-black text-xl hover:bg-purple-50 transition-all shadow-2xl">Launch WACC Wizard →</button></div></section>

        <section><h2 className="text-3xl font-black text-slate-900 mb-6">Continue Learning</h2><div className="grid md:grid-cols-3 gap-6"><button onClick={() => setActiveTool(ToolType.ACADEMY_DCF_GUIDE)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-purple-500"><div className="text-3xl mb-3">📊</div><h3 className="font-black text-slate-900 mb-2">DCF Valuation Guide</h3><p className="text-slate-600 text-sm">Complete stock valuation walkthrough</p></button><button onClick={() => setActiveTool(ToolType.ACADEMY_GREEKS_GUIDE)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-purple-500"><div className="text-3xl mb-3">📈</div><h3 className="font-black text-slate-900 mb-2">Options Greeks</h3><p className="text-slate-600 text-sm">Master Delta, Theta, Vega, Gamma</p></button><button onClick={() => setActiveTool(ToolType.VALUATION_ACADEMY)} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-all text-left border-2 border-transparent hover:border-purple-500"><div className="text-3xl mb-3">🎓</div><h3 className="font-black text-slate-900 mb-2">All Guides</h3><p className="text-slate-600 text-sm">Back to Academy</p></button></div></section>
      </article>
    </div>
  );
};

export default WACCGuide;
