/**
 * PDF Generation Service
 * 
 * Creates PDF lead magnets (checklists, templates, guides)
 * Uses browser's print functionality or jsPDF library
 * 
 * TODO: Consider using jsPDF or PDFKit for more advanced PDF generation
 */

export interface PDFContent {
  title: string;
  sections: PDFSection[];
  footer?: string;
}

export interface PDFSection {
  title: string;
  items: string[];
  type?: 'checklist' | 'guide' | 'template';
}

class PDFService {
  /**
   * Generate a PDF from content
   */
  async generatePDF(content: PDFContent): Promise<Blob | null> {
    try {
      // Create HTML content for PDF
      const htmlContent = this.createHTMLContent(content);
      
      // Create a temporary window for printing
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        console.error('Popup blocked - cannot generate PDF');
        return null;
      }

      printWindow.document.write(htmlContent);
      printWindow.document.close();

      // Wait for content to load, then trigger print
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
        }, 250);
      };

      // For actual PDF download, we'd use jsPDF or similar
      // For now, this triggers browser print-to-PDF
      return null;
    } catch (error) {
      console.error('PDF generation error:', error);
      return null;
    }
  }

  /**
   * Create HTML content for PDF
   */
  private createHTMLContent(content: PDFContent): string {
    return `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${content.title}</title>
          <style>
            @media print {
              @page { margin: 1in; }
              body { font-family: Arial, sans-serif; }
            }
            body {
              font-family: Arial, sans-serif;
              max-width: 8.5in;
              margin: 0 auto;
              padding: 20px;
              line-height: 1.6;
            }
            h1 {
              color: #4f46e5;
              border-bottom: 3px solid #4f46e5;
              padding-bottom: 10px;
              margin-bottom: 30px;
            }
            h2 {
              color: #1e293b;
              margin-top: 30px;
              margin-bottom: 15px;
            }
            .section {
              margin-bottom: 25px;
            }
            .checklist-item {
              margin: 8px 0;
              padding-left: 25px;
              position: relative;
            }
            .checklist-item:before {
              content: "☐";
              position: absolute;
              left: 0;
              font-size: 18px;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e2e8f0;
              font-size: 12px;
              color: #64748b;
              text-align: center;
            }
          </style>
        </head>
        <body>
          <h1>${content.title}</h1>
          ${content.sections.map(section => `
            <div class="section">
              <h2>${section.title}</h2>
              ${section.items.map(item => `
                <div class="checklist-item">${item}</div>
              `).join('')}
            </div>
          `).join('')}
          ${content.footer ? `<div class="footer">${content.footer}</div>` : ''}
          <div class="footer">
            <p>Generated by QuantCurb - quantcurb.com</p>
            <p>© 2025 QuantCurb Intelligence. For educational purposes only.</p>
          </div>
        </body>
      </html>
    `;
  }

  /**
   * Generate Mortgage Planning Checklist PDF
   */
  generateMortgageChecklist(): PDFContent {
    return {
      title: "Mortgage Planning Checklist 2025",
      sections: [
        {
          title: "Pre-Approval Preparation",
          type: 'checklist',
          items: [
            "Check your credit score (aim for 720+)",
            "Gather financial documents (W-2s, tax returns, bank statements)",
            "Calculate your debt-to-income ratio (target <36%)",
            "Save for down payment (aim for 20% to avoid PMI)",
            "Save for closing costs (2-5% of home price)",
            "Get pre-approved from multiple lenders"
          ]
        },
        {
          title: "Home Search & Offer",
          type: 'checklist',
          items: [
            "Determine your maximum home price (use 28/36 rule)",
            "Research neighborhoods and school districts",
            "Get pre-approved before house hunting",
            "Hire a real estate agent",
            "Make competitive offers with contingencies",
            "Schedule home inspection"
          ]
        },
        {
          title: "Mortgage Application",
          type: 'checklist',
          items: [
            "Compare loan offers (APR, fees, terms)",
            "Choose loan type (30-year vs 15-year fixed, ARM)",
            "Lock in interest rate",
            "Complete mortgage application",
            "Provide all required documentation",
            "Review Loan Estimate and Closing Disclosure"
          ]
        },
        {
          title: "Closing Preparation",
          type: 'checklist',
          items: [
            "Review closing costs breakdown",
            "Arrange homeowners insurance",
            "Schedule final walkthrough",
            "Bring certified check for closing costs",
            "Review all documents before signing",
            "Keep copies of all closing documents"
          ]
        }
      ],
      footer: "Use QuantCurb's Mortgage Calculator to estimate your monthly PITI payment: quantcurb.com/mortgage-payment-calculator"
    };
  }

  /**
   * Generate Quarterly Tax Checklist PDF
   */
  generateQuarterlyTaxChecklist(): PDFContent {
    return {
      title: "Quarterly Estimated Tax Checklist 2025",
      sections: [
        {
          title: "Q1 Payment (Due April 15, 2025)",
          type: 'checklist',
          items: [
            "Calculate Q1 income (Jan-Mar)",
            "Estimate self-employment tax (15.3%)",
            "Calculate federal income tax",
            "Apply safe harbor rules (100%/110% prior year or 90% current)",
            "Make payment via IRS Direct Pay or EFTPS",
            "Save payment confirmation"
          ]
        },
        {
          title: "Q2 Payment (Due June 16, 2025)",
          type: 'checklist',
          items: [
            "Calculate Q2 income (Apr-Jun)",
            "Recalculate year-to-date estimates",
            "Adjust payment if income changed",
            "Make payment by deadline",
            "Track all payments for annual return"
          ]
        },
        {
          title: "Q3 Payment (Due September 15, 2025)",
          type: 'checklist',
          items: [
            "Calculate Q3 income (Jul-Sep)",
            "Review year-to-date totals",
            "Estimate full-year tax liability",
            "Make payment by deadline",
            "Consider increasing payment if income up"
          ]
        },
        {
          title: "Q4 Payment (Due January 15, 2026)",
          type: 'checklist',
          items: [
            "Calculate Q4 income (Oct-Dec)",
            "Finalize full-year estimates",
            "Make final quarterly payment",
            "Prepare for annual tax return",
            "Gather all 1099s and income records"
          ]
        },
        {
          title: "Safe Harbor Rules",
          type: 'guide',
          items: [
            "100% of prior year's tax (110% if AGI >$150k)",
            "OR 90% of current year's tax",
            "Whichever is lower = safe harbor amount",
            "If you meet safe harbor, no penalties even if you underpay"
          ]
        }
      ],
      footer: "Use QuantCurb's Quarterly Tax Calculator: quantcurb.com/quarterly-estimated-tax-calculator"
    };
  }

  /**
   * Generate Freelancer Tax Deduction Guide PDF
   */
  generateFreelancerTaxDeductionGuide(): PDFContent {
    return {
      title: "Freelancer Tax Deduction Guide 2025",
      sections: [
        {
          title: "Home Office Deduction",
          type: 'checklist',
          items: [
            "Simplified method: $5/sq ft (max $1,500)",
            "OR Regular method: Actual expenses × business use %",
            "Must be exclusive business use",
            "Must be principal place of business",
            "Document with photos and measurements"
          ]
        },
        {
          title: "Vehicle & Travel Expenses",
          type: 'checklist',
          items: [
            "Mileage deduction: $0.67/mile (2025)",
            "OR Actual expenses (gas, maintenance, depreciation)",
            "Track all business miles with app",
            "Parking and tolls (100% deductible)",
            "Business travel (hotels, meals 50% deductible)"
          ]
        },
        {
          title: "Equipment & Software",
          type: 'checklist',
          items: [
            "Computers, phones, tablets (Section 179 or depreciation)",
            "Software subscriptions (100% deductible)",
            "Office furniture and supplies",
            "Internet and phone (business portion)",
            "Cloud storage and backup services"
          ]
        },
        {
          title: "Professional Services",
          type: 'checklist',
          items: [
            "Accounting and bookkeeping fees",
            "Legal fees (business-related)",
            "Professional development courses",
            "Conference and workshop fees",
            "Professional association memberships"
          ]
        },
        {
          title: "Health Insurance & Retirement",
          type: 'checklist',
          items: [
            "Health insurance premiums (100% deductible)",
            "HSA contributions (triple tax advantage)",
            "SEP-IRA or Solo 401(k) contributions",
            "Long-term care insurance (age-based limits)"
          ]
        }
      ],
      footer: "Use QuantCurb's Freelance Profit Hub: quantcurb.com/freelance-profit-hub"
    };
  }

  /**
   * Generate FIRE Planning Workbook PDF
   */
  generateFIREWorkbook(): PDFContent {
    return {
      title: "FIRE Planning Workbook 2025",
      sections: [
        {
          title: "Calculate Your FIRE Number",
          type: 'template',
          items: [
            "Annual Expenses: $__________",
            "FIRE Number (Expenses × 25): $__________",
            "Current Savings: $__________",
            "Gap to FIRE: $__________",
            "Monthly Savings Needed: $__________"
          ]
        },
        {
          title: "Optimize Your Savings Rate",
          type: 'checklist',
          items: [
            "Track all expenses for 1 month",
            "Identify non-essential spending",
            "Set savings rate goal (50%+ for FIRE)",
            "Automate investments",
            "Increase income (raises, side hustles)",
            "Reduce expenses (housing, transportation, food)"
          ]
        },
        {
          title: "Investment Strategy",
          type: 'checklist',
          items: [
            "Maximize 401(k) contributions ($23,000 in 2025)",
            "Contribute to IRA ($7,000 in 2025)",
            "Invest in low-cost index funds (VTSAX, VTI)",
            "Automate monthly investments",
            "Avoid high-fee investments",
            "Rebalance portfolio annually"
          ]
        },
        {
          title: "FIRE Milestones",
          type: 'template',
          items: [
            "25% to FIRE: $__________ (Date: __________)",
            "50% to FIRE: $__________ (Date: __________)",
            "75% to FIRE: $__________ (Date: __________)",
            "100% to FIRE: $__________ (Date: __________)",
            "Target Retirement Date: __________"
          ]
        }
      ],
      footer: "Use QuantCurb's FIRE Planner: quantcurb.com/early-retirement-fire-planner"
    };
  }
}

export const pdfService = new PDFService();
