/**
 * Long-tail keyword strategy for all QuantCurb tools
 *
 * Organized by:
 * - Primary keywords (high volume, high competition)
 * - Long-tail keywords (lower volume, lower competition, higher intent)
 * - Question-based keywords (voice search, featured snippets)
 * - Comparison keywords (vs, versus, compared to)
 * - Location-based keywords (by state, by city)
 */

import { ToolType } from '../types';

export interface KeywordSet {
  primary: string[];
  longTail: string[];
  questions: string[];
  comparisons: string[];
  locations: string[];
  monthlySearchVolume: number; // Combined estimated volume
  difficulty: 'Low' | 'Medium' | 'High';
}

export const TOOL_KEYWORDS: Partial<Record<ToolType, KeywordSet>> = {
  [ToolType.FIRE_PLANNER]: {
    primary: [
      'fire calculator',
      'early retirement calculator',
      'financial independence calculator',
    ],
    longTail: [
      'how to calculate fire number',
      'early retirement calculator with inflation',
      'fire calculator with social security',
      'coast fire calculator',
      'lean fire calculator',
      'fat fire calculator',
      'barista fire calculator',
      'fire retirement age calculator',
      'financial independence retire early calculator',
      'passive income retirement calculator',
      '4 percent rule calculator',
      '3 percent rule calculator',
      'safe withdrawal rate calculator',
      'retirement savings calculator by age',
      'how much to retire at 40',
      'how much to retire at 45',
      'how much to retire at 50',
      'retire early with 1 million',
      'retire early with 500k',
      'retirement calculator with side income',
      'fire calculator with real estate income',
    ],
    questions: [
      'how much money do i need to fire',
      'when can i retire early',
      'what is my fire number',
      'how to calculate financial independence',
      'is fire realistic',
      'how long until i can retire',
      'can i retire at 55 with 2 million',
      'can i retire at 60 with 1 million',
      'how much do i need to retire comfortably',
      'what is the 4 percent rule',
      'how does early retirement work',
    ],
    comparisons: [
      'fire calculator vs retirement calculator',
      'lean fire vs fat fire',
      'coast fire vs regular fire',
      '3 percent vs 4 percent rule',
    ],
    locations: [
      '[state] early retirement calculator',
      'retire early in [state]',
      '[state] fire calculator',
      'cost to retire in [state]',
    ],
    monthlySearchVolume: 35000,
    difficulty: 'Medium',
  },

  [ToolType.MORTGAGE_CALC]: {
    primary: [
      'mortgage calculator',
      'home loan calculator',
      'mortgage payment calculator',
    ],
    longTail: [
      'how to calculate mortgage payment',
      'mortgage calculator with pmi',
      'mortgage calculator with property tax',
      'mortgage calculator with hoa',
      'mortgage calculator with extra payments',
      'biweekly mortgage calculator',
      'mortgage calculator with insurance',
      'mortgage calculator piti breakdown',
      'fha loan calculator with pmi',
      'va loan calculator',
      'jumbo mortgage calculator',
      '15 year vs 30 year mortgage calculator',
      'mortgage payoff calculator with extra payments',
      'how much mortgage can i afford calculator',
      'mortgage points calculator',
      'mortgage closing costs calculator',
      'mortgage amortization calculator',
      'mortgage refinance calculator',
      'mortgage rate comparison calculator',
      'first time home buyer mortgage calculator',
      'mortgage affordability calculator',
      'mortgage payment breakdown calculator',
      'mortgage interest calculator',
      'mortgage principal calculator',
      'when does pmi drop off calculator',
    ],
    questions: [
      'how to calculate mortgage payment manually',
      'how much house can i afford',
      'what is piti in mortgage',
      'how is mortgage calculated',
      'when can i remove pmi',
      'what is included in mortgage payment',
      'how to calculate property tax on house',
      'what are closing costs',
      'how much is pmi per month',
      'should i pay points on mortgage',
      'is fha loan worth it',
      'how to calculate mortgage interest',
    ],
    comparisons: [
      '15 year vs 30 year mortgage',
      'fha vs conventional loan',
      'fixed vs arm mortgage',
      'buying vs renting calculator',
      'mortgage vs rent comparison',
    ],
    locations: [
      '[state] mortgage calculator',
      '[state] property tax calculator',
      '[city] mortgage calculator',
      'mortgage rates in [state]',
    ],
    monthlySearchVolume: 450000,
    difficulty: 'High',
  },

  [ToolType.SALARY_CALC]: {
    primary: [
      'salary calculator',
      'take home pay calculator',
      'paycheck calculator',
    ],
    longTail: [
      'how to calculate take home pay',
      'salary after tax calculator',
      'net pay calculator after taxes',
      'biweekly paycheck calculator',
      'hourly to salary calculator after tax',
      'salary calculator with 401k',
      'gross to net salary calculator',
      'salary tax calculator by state',
      'paycheck calculator with pre tax deductions',
      'salary calculator after federal and state tax',
      'take home pay calculator after 401k',
      'salary to hourly after tax calculator',
      'annual salary to monthly take home',
      '100k salary take home',
      '150k salary after taxes',
      '200k salary take home',
      'how much is 80k after taxes',
      'paycheck calculator california',
      'paycheck calculator texas',
      'paycheck calculator new york',
    ],
    questions: [
      'how much will i take home',
      'how to calculate net pay from gross',
      'what is my take home pay',
      'how much tax on 100k salary',
      'how is paycheck calculated',
      'what percentage of paycheck goes to taxes',
      'how much fica tax on salary',
      'how to increase take home pay',
    ],
    comparisons: [
      'california vs texas salary',
      'new york vs florida take home pay',
      'gross pay vs net pay',
      'w2 vs 1099 take home pay',
    ],
    locations: [
      '[state] salary calculator',
      '[state] take home pay',
      '[state] paycheck calculator',
      'take home pay in [city]',
    ],
    monthlySearchVolume: 380000,
    difficulty: 'High',
  },

  [ToolType.QUARTERLY_TAX]: {
    primary: [
      'quarterly tax calculator',
      'estimated tax calculator',
      'quarterly taxes calculator',
    ],
    longTail: [
      'how to calculate quarterly taxes',
      'freelance quarterly tax calculator',
      'self employed quarterly tax calculator',
      '1099 quarterly tax calculator',
      'safe harbor quarterly tax calculator',
      'quarterly estimated tax calculator irs',
      'quarterly tax payment calculator',
      'how much to pay quarterly taxes',
      'quarterly tax deadline calculator',
      'self employment tax quarterly calculator',
      'estimated quarterly tax worksheet',
      'quarterly tax calculator with safe harbor',
      'how to avoid underpayment penalty',
      '110 percent safe harbor calculator',
      '100 percent prior year tax calculator',
    ],
    questions: [
      'how to calculate quarterly taxes for self employed',
      'do i need to pay quarterly taxes',
      'when are quarterly taxes due',
      'how much should i pay in quarterly taxes',
      'what is safe harbor for taxes',
      'how to avoid quarterly tax penalty',
      'what happens if i miss quarterly taxes',
      'how to pay quarterly estimated taxes',
      'who needs to pay quarterly taxes',
    ],
    comparisons: [
      'safe harbor vs 90 percent method',
      'quarterly taxes vs annual taxes',
      'prior year method vs current year method',
    ],
    locations: [
      '[state] quarterly tax calculator',
      'quarterly taxes in [state]',
      '[state] self employment tax',
    ],
    monthlySearchVolume: 28000,
    difficulty: 'Medium',
  },

  [ToolType.OPTIONS_STRATEGY_VISUALIZER]: {
    primary: [
      'options calculator',
      'options strategy calculator',
      'options profit calculator',
    ],
    longTail: [
      'iron condor calculator',
      'bull call spread calculator',
      'bear put spread calculator',
      'straddle calculator',
      'strangle calculator',
      'butterfly spread calculator',
      'credit spread calculator',
      'debit spread calculator',
      'options greeks calculator',
      'options profit loss calculator',
      'multi leg options calculator',
      'vertical spread calculator',
      'calendar spread calculator',
      'diagonal spread calculator',
      'options breakeven calculator',
      'options max profit calculator',
      'options probability calculator',
      'covered call calculator',
      'cash secured put calculator',
      'collar strategy calculator',
      'ratio spread calculator',
    ],
    questions: [
      'how to calculate options profit',
      'what is iron condor strategy',
      'how to trade credit spreads',
      'what are options greeks',
      'how does delta work in options',
      'what is theta decay',
      'how to calculate breakeven for options',
      'when to close iron condor',
      'how to manage options spreads',
    ],
    comparisons: [
      'iron condor vs iron butterfly',
      'call spread vs put spread',
      'straddle vs strangle',
      'vertical spread vs diagonal spread',
      'credit spread vs debit spread',
    ],
    locations: [
      'options trading calculator',
      'spy options calculator',
      'qqq options calculator',
    ],
    monthlySearchVolume: 22000,
    difficulty: 'Medium',
  },

  [ToolType.EXCEL_MODELER]: {
    primary: [
      'dcf calculator',
      'stock valuation calculator',
      'dcf model',
    ],
    longTail: [
      'discounted cash flow calculator',
      'wacc calculator',
      'terminal value calculator',
      'free cash flow calculator',
      'dcf valuation calculator',
      'stock intrinsic value calculator',
      'enterprise value calculator',
      'equity value calculator',
      'fcf projection calculator',
      'how to calculate dcf',
      'how to value a stock dcf',
      'wacc calculator with beta',
      'cost of equity calculator',
      'cost of debt calculator',
      'capm calculator',
      'perpetuity growth method calculator',
      'exit multiple calculator',
      'fcff calculator',
      'fcfe calculator',
    ],
    questions: [
      'how to calculate dcf valuation',
      'what is wacc formula',
      'how to calculate terminal value',
      'how to value a company using dcf',
      'what is a good wacc',
      'how to calculate free cash flow',
      'how to calculate intrinsic value',
      'what is enterprise value vs equity value',
      'how to calculate cost of equity',
    ],
    comparisons: [
      'dcf vs comparable companies',
      'fcff vs fcfe',
      'enterprise value vs equity value',
      'wacc vs capm',
      'terminal value methods comparison',
    ],
    locations: [],
    monthlySearchVolume: 18000,
    difficulty: 'Medium',
  },

  [ToolType.FREELANCE_PROFIT]: {
    primary: [
      'freelance calculator',
      'self employment tax calculator',
      'freelance profit calculator',
    ],
    longTail: [
      'how to calculate self employment tax',
      '1099 tax calculator',
      'freelance income tax calculator',
      'self employed tax calculator 2026',
      'freelance hourly rate calculator',
      'freelance pricing calculator',
      'contractor tax calculator',
      'gig worker tax calculator',
      'uber tax calculator',
      'doordash tax calculator',
      'self employment tax rate calculator',
      'freelance business expense calculator',
      'home office deduction calculator',
      'qbi deduction calculator',
      's corp tax savings calculator',
      'llc vs sole proprietor calculator',
    ],
    questions: [
      'how much tax do freelancers pay',
      'how to calculate 1099 taxes',
      'what is self employment tax rate',
      'how much should i charge as a freelancer',
      'what can freelancers deduct',
      'should i form an llc as a freelancer',
      'how to reduce self employment tax',
      'do i need to pay quarterly taxes as a freelancer',
    ],
    comparisons: [
      '1099 vs w2 calculator',
      'llc vs s corp for freelancers',
      'sole proprietor vs llc',
      'freelance vs employee taxes',
    ],
    locations: [
      '[state] freelance tax calculator',
      '[state] self employment tax',
      'freelance taxes in [state]',
    ],
    monthlySearchVolume: 45000,
    difficulty: 'Medium',
  },

  [ToolType.CHILD_TAX_CREDIT]: {
    primary: [
      'child tax credit calculator',
      'ctc calculator',
      'child tax credit 2026',
    ],
    longTail: [
      'how much is child tax credit 2026',
      'child tax credit eligibility calculator',
      'child tax credit income limit',
      'child tax credit phaseout calculator',
      'additional child tax credit calculator',
      'child tax credit per child',
      'refundable child tax credit',
      'child tax credit age limit',
      'how to calculate child tax credit',
      'will i get child tax credit',
      'child tax credit modified agi calculator',
    ],
    questions: [
      'how much is child tax credit',
      'who qualifies for child tax credit',
      'what is the income limit for child tax credit',
      'at what income does child tax credit phase out',
      'how many children qualify for ctc',
      'is child tax credit refundable',
      'how to claim child tax credit',
    ],
    comparisons: [
      'child tax credit vs earned income credit',
      'ctc vs eitc',
      'child tax credit vs dependent care credit',
    ],
    locations: [],
    monthlySearchVolume: 95000,
    difficulty: 'Low',
  },

  [ToolType.ACA_SUBSIDY]: {
    primary: [
      'aca subsidy calculator',
      'health insurance subsidy calculator',
      'obamacare calculator',
    ],
    longTail: [
      'marketplace subsidy calculator',
      'premium tax credit calculator',
      'aca affordability calculator',
      'health insurance marketplace calculator',
      'obamacare subsidy calculator 2026',
      'how much is aca subsidy',
      'health insurance tax credit calculator',
      'cobra vs aca calculator',
      'early retirement health insurance calculator',
    ],
    questions: [
      'how much is aca subsidy',
      'who qualifies for aca subsidy',
      'how to calculate aca subsidy',
      'what income qualifies for obamacare subsidy',
      'how does aca subsidy work',
      'is aca subsidy based on gross income',
    ],
    comparisons: [
      'aca vs cobra',
      'marketplace vs employer insurance',
      'silver plan vs gold plan',
    ],
    locations: [
      '[state] aca subsidy',
      '[state] health insurance marketplace',
      'obamacare in [state]',
    ],
    monthlySearchVolume: 52000,
    difficulty: 'Medium',
  },

  [ToolType.NET_WORTH]: {
    primary: [
      'net worth calculator',
      'net worth tracker',
      'calculate net worth',
    ],
    longTail: [
      'how to calculate net worth',
      'net worth calculator by age',
      'personal net worth calculator',
      'net worth percentile calculator',
      'average net worth by age calculator',
      'liquid net worth calculator',
      'household net worth calculator',
      'net worth goal calculator',
      'debt to asset ratio calculator',
      'liquidity ratio calculator',
    ],
    questions: [
      'how to calculate net worth',
      'what is net worth',
      'what should my net worth be',
      'how to increase net worth',
      'what is a good net worth by age',
      'what counts as assets for net worth',
      'should i include home in net worth',
    ],
    comparisons: [
      'net worth vs income',
      'liquid net worth vs total net worth',
      'assets vs liabilities',
    ],
    locations: [
      'average net worth in [state]',
      '[state] net worth calculator',
    ],
    monthlySearchVolume: 65000,
    difficulty: 'Medium',
  },

  [ToolType.INVESTMENT_CALC]: {
    primary: [
      'investment calculator',
      'compound interest calculator',
      'sip calculator',
    ],
    longTail: [
      'how to calculate investment growth',
      'compound interest calculator monthly',
      'investment return calculator',
      'portfolio growth calculator',
      'retirement investment calculator',
      'monthly investment calculator',
      'lump sum investment calculator',
      'investment calculator with inflation',
      'stock market return calculator',
      'mutual fund calculator',
      'index fund calculator',
      'dividend reinvestment calculator',
      'drip calculator',
      '401k growth calculator',
      'roth ira growth calculator',
      'investment doubling calculator',
      'rule of 72 calculator',
    ],
    questions: [
      'how much will my investment grow',
      'how to calculate compound interest',
      'how long to double investment',
      'what is compound interest formula',
      'how much should i invest monthly',
      'what is a good investment return',
    ],
    comparisons: [
      'lump sum vs dollar cost averaging',
      'monthly vs annual investing',
      'compound interest vs simple interest',
    ],
    locations: [],
    monthlySearchVolume: 125000,
    difficulty: 'High',
  },

  [ToolType.RETIREMENT_OPTIMIZER]: {
    primary: [
      'retirement calculator',
      '401k calculator',
      'roth ira calculator',
    ],
    longTail: [
      'how much to save for retirement',
      'retirement savings calculator by age',
      '401k contribution calculator',
      'roth vs traditional calculator',
      'backdoor roth calculator',
      'mega backdoor roth calculator',
      'roth conversion calculator',
      'retirement account optimizer',
      'tax efficient retirement calculator',
      'retirement withdrawal calculator',
      'required minimum distribution calculator',
      'rmd calculator',
      'retirement tax calculator',
      'social security retirement calculator',
      'pension vs 401k calculator',
    ],
    questions: [
      'how much should i contribute to 401k',
      'should i do roth or traditional 401k',
      'how much to retire comfortably',
      'what is backdoor roth ira',
      'how does mega backdoor roth work',
      'when can i withdraw from 401k',
      'what is roth conversion',
    ],
    comparisons: [
      'roth vs traditional 401k',
      'roth ira vs traditional ira',
      '401k vs ira',
      'sep ira vs solo 401k',
    ],
    locations: [],
    monthlySearchVolume: 215000,
    difficulty: 'High',
  },

  [ToolType.EMI_CALC]: {
    primary: [
      'emi calculator',
      'loan calculator',
      'loan repayment calculator',
    ],
    longTail: [
      'how to calculate emi',
      'loan emi calculator with prepayment',
      'home loan emi calculator',
      'car loan emi calculator',
      'personal loan emi calculator',
      'education loan emi calculator',
      'emi calculator with interest rate',
      'reducing balance emi calculator',
      'loan amortization calculator',
      'extra payment loan calculator',
      'loan payoff calculator with extra payments',
    ],
    questions: [
      'how to calculate emi manually',
      'what is emi formula',
      'how is emi calculated',
      'how to reduce emi',
      'what happens if i pay extra emi',
      'how to calculate loan interest',
    ],
    comparisons: [
      'flat rate vs reducing balance',
      'prepayment vs regular payment',
      'fixed rate vs floating rate',
    ],
    locations: [
      '[state] loan calculator',
    ],
    monthlySearchVolume: 185000,
    difficulty: 'Medium',
  },

  // Add more tools...
  [ToolType.DASHBOARD]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.EMERGENCY_FUND]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.MARKET_INSIGHTS]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.LOAN_COMPARE]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.LIVING_COST]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.CURRENCY_CONV]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.GST_CALC]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.CREDIT_CARD_PAYOFF]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.INVESTMENT_ACADEMY]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.DRIP_CALCULATOR]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.CRYPTO_TAX_LOSS]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.DTI_CALCULATOR]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.VALUATION_ACADEMY]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_DCF_GUIDE]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_WACC_GUIDE]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_GREEKS_GUIDE]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_SAFE_HARBOR]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_IRON_CONDOR]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
  [ToolType.ACADEMY_STATE_TAX_COMPARISON]: {
    primary: [],
    longTail: [],
    questions: [],
    comparisons: [],
    locations: [],
    monthlySearchVolume: 0,
    difficulty: 'Low',
  },
};

// Helper function to get all keywords for a tool
export function getAllKeywords(toolType: ToolType): string[] {
  const keywords = TOOL_KEYWORDS[toolType];
  if (!keywords) return [];

  return [
    ...keywords.primary,
    ...keywords.longTail,
    ...keywords.questions,
    ...keywords.comparisons,
  ];
}

// Helper function to get question keywords for FAQ schema
export function getQuestionKeywords(toolType: ToolType): string[] {
  const keywords = TOOL_KEYWORDS[toolType];
  return keywords?.questions || [];
}

// Get comparison keywords for vs pages
export function getComparisonKeywords(toolType: ToolType): string[] {
  const keywords = TOOL_KEYWORDS[toolType];
  return keywords?.comparisons || [];
}
